# Generated by Django 6.0.1 on 2026-01-24 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("office", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=100, unique=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="feedback.feedbacktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("rating", "Rating"),
                            ("choice", "Choice"),
                            ("checkbox", "Checkbox"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="feedback.feedbacktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_value", models.TextField(blank=True, null=True)),
                ("number_value", models.FloatField(blank=True, null=True)),
                ("rating_value", models.IntegerField(blank=True, null=True)),
                (
                    "choice_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("checkbox_values", models.JSONField(blank=True, default=list)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="feedback.feedbackresponse",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="feedback.templatefield",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="feedbacktemplate",
            index=models.Index(
                fields=["status", "office"], name="feedback_fe_status_bebaae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbacktemplate",
            index=models.Index(
                fields=["created_by", "status"], name="feedback_fe_created_4a8858_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackresponse",
            index=models.Index(
                fields=["template", "submitted_at"],
                name="feedback_fe_templat_63f527_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackresponse",
            index=models.Index(
                fields=["session_token"], name="feedback_fe_session_fc603b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templatefield",
            index=models.Index(
                fields=["template", "order"], name="feedback_te_templat_653b33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackanswer",
            index=models.Index(
                fields=["response", "field"], name="feedback_fe_respons_99258f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedbackanswer",
            unique_together={("response", "field")},
        ),
    ]
