# Generated by Django 6.0.1 on 2026-01-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacktemplate",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedbacktemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedbacktemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("acknowledgment", "Acknowledgment"),
                    ("progress", "Progress Update"),
                    ("resolution", "Resolution"),
                    ("follow-up", "Follow-up"),
                    ("assessment", "Service Assessment"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="feedbacktemplate",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedbacktemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("feedback", "Feedback Template"),
                    ("service_assessment", "Service Assessment"),
                ],
                default="feedback",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="feedbacktemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("inactive", "Inactive"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
