# Generated by Django 6.0.1 on 2026-01-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_add_user_to_feedbackresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbacktemplate",
            name="category",
        ),
        migrations.RemoveField(
            model_name="feedbacktemplate",
            name="template_type",
        ),
    ]
