# Generated by Django 6.0.1 on 2026-03-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIPriorityKeyword",
        ),
        migrations.DeleteModel(
            name="AISettingsConfig",
        ),
    ]
