# Generated by Django 6.0.1 on 2026-03-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintCC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cc_list",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "unique_together": {("complaint", "email")},
            },
        ),
    ]
