# Generated by Django 6.0.1 on 2026-01-22 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_response"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_type",
            field=models.CharField(
                choices=[("comment", "Comment"), ("rating", "Rating")],
                default="comment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                blank=True, help_text="Rating from 1 to 5 stars", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["complaint", "comment_type"],
                name="complaints__complai_1b8529_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "created_at"], name="complaints__author__b53f24_idx"
            ),
        ),
    ]
