# Generated by Django 6.0.1 on 2026-01-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_comment_comment_type_comment_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_amharic",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_amharic",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
