# Generated by Django 6.0.1 on 2026-01-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPriorityKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("word", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["priority", "word"],
            },
        ),
        migrations.CreateModel(
            name="AISettingsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_category", models.BooleanField(default=True)),
                ("auto_assignment", models.BooleanField(default=False)),
                ("auto_priority", models.BooleanField(default=True)),
                ("smart_routing", models.BooleanField(default=True)),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("workload_based", "Workload Based"),
                            ("expertise_based", "Expertise Based"),
                            ("random", "Random"),
                        ],
                        default="workload_based",
                        max_length=30,
                    ),
                ),
                ("confidence_threshold", models.PositiveIntegerField(default=85)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("learning_mode", models.BooleanField(default=True)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="complaints__user_id_0f3b56_idx",
            old_name="complaints_n_user_id_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="complaints__notific_a3225d_idx",
            old_name="complaints_n_notifi_d4e5f6_idx",
        ),
        migrations.AlterUniqueTogether(
            name="aiprioritykeyword",
            unique_together={("priority", "word")},
        ),
    ]
