# Generated by Django 6.0.1 on 2026-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('CMHS', 'College of Medicine and Health Sciences'), ('CNCS', 'College of Natural and Computational Sciences'), ('CBE', 'College of Business and Economics'), ('CSSH', 'College of Social Sciences and Humanities'), ('CVMAS', 'College of Veterinary Medicine and Animal Sciences'), ('CAES', 'College of Agriculture and Environmental Sciences'), ('COI', 'College of Informatics'), ('COE', 'College of Education'), ('IOT', 'Institute of Technology'), ('IOB', 'Institute of Biotechnology'), ('SOL', 'School of Law')], max_length=100, null=True),
        ),
    ]
